// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqwpHhtGrvVRwqoGww0R1fVdOIETyy0_I',
    appId: '1:209596339220:web:698c83c093d8bebce34301',
    messagingSenderId: '209596339220',
    projectId: 'bioreactor-bb6b7',
    authDomain: 'bioreactor-bb6b7.firebaseapp.com',
    databaseURL: 'https://bioreactor-bb6b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bioreactor-bb6b7.appspot.com',
    measurementId: 'G-S8L9D4GBDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-oSz3NV77CNDToN0Ryw-qG_qulCDdNC4',
    appId: '1:209596339220:android:19b4f0de873885f3e34301',
    messagingSenderId: '209596339220',
    projectId: 'bioreactor-bb6b7',
    databaseURL: 'https://bioreactor-bb6b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bioreactor-bb6b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADMyUiZ7cVlqIIz_Y7tDqS72RU5SsE-pA',
    appId: '1:209596339220:ios:c89cc8ce767a4f59e34301',
    messagingSenderId: '209596339220',
    projectId: 'bioreactor-bb6b7',
    databaseURL: 'https://bioreactor-bb6b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bioreactor-bb6b7.appspot.com',
    iosClientId: '209596339220-floq0gqb0t1h811o5t5567fn2qq4do7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.bioReactorWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADMyUiZ7cVlqIIz_Y7tDqS72RU5SsE-pA',
    appId: '1:209596339220:ios:c89cc8ce767a4f59e34301',
    messagingSenderId: '209596339220',
    projectId: 'bioreactor-bb6b7',
    databaseURL: 'https://bioreactor-bb6b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bioreactor-bb6b7.appspot.com',
    iosClientId: '209596339220-floq0gqb0t1h811o5t5567fn2qq4do7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.bioReactorWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqwpHhtGrvVRwqoGww0R1fVdOIETyy0_I',
    appId: '1:209596339220:web:1a18af9b8c045061e34301',
    messagingSenderId: '209596339220',
    projectId: 'bioreactor-bb6b7',
    authDomain: 'bioreactor-bb6b7.firebaseapp.com',
    databaseURL: 'https://bioreactor-bb6b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bioreactor-bb6b7.appspot.com',
    measurementId: 'G-DFCWPK1QNK',
  );
}
